generatorName: go
templateDir: ./.generator/templates
outputDir: ./okta/v6
gitUserId: okta
gitRepoId: okta-sdk-golang
versionName: v6
goVersion: "1.23.0"
toolchainVersion: "go1.24.0"
additionalProperties:
  enumClassPrefix: true
  generateInterfaces: true
  packageName: okta
  packageVersion: 6.0.1
  useOneOfDiscriminatorLookup: true
  disallowAdditionalPropertiesIfNotPresent: false
files:
  asset/logo.png: {}
  cache_test.go: {}
  cache.go: {}
  client_retry_test.go: {}
  configuration_test.go: {}
  gocache.go: {}
  noopcache.go: {}
  proxy_test.go: {}
  user_agent.go: {}
  test_helpers.go: {}
  test_data_manager.go: {}
